### ISSUE TITLE
Change gem & repo name to underscore casing to match ruby idioms?

### ISSUE THREAD

**Issue by Jarred-Sumner** [macebake/emojify-rspec_formatter#1]
The gem name is currently `EmojifyRspecFormatter`. It is more idiomatic ruby to use underscore case or dashes for gem names instead of camel case. This would make the gem name `emojify_rspec_formatter` or `emojify-rspec-formatter`. 

It's also better if the repo name (`macebake/emojify-rspec_formatter`) matches the gem name, so the gem to add to the `Gemfile` is more guessable and consistent.

These are minor things though! The gem looks cool.

**Comment by macebake** [comment]
Good point! All fixed! 😍
